"""Add date and time fields to Event

Revision ID: 220d5cd5679e
Revises: f35095d5e2e9
Create Date: 2024-10-12 17:36:12.794895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220d5cd5679e'
down_revision = 'f35095d5e2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
