"""Add profile fields to User model

Revision ID: f35095d5e2e9
Revises: 
Create Date: 2024-10-12 15:50:21.129101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35095d5e2e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sports', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('location_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('school_work', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('school_work')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('gender')
        batch_op.drop_column('languages')
        batch_op.drop_column('location_state')
        batch_op.drop_column('location_city')
        batch_op.drop_column('interests')
        batch_op.drop_column('sports')
        batch_op.drop_column('age')
        batch_op.drop_column('bio')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
